Repository cncjs/cncjs, pull requests merged in 2019-04, with the labels that each got.

#450 Fix an issue that dropdown menu gets clipped by container with overflow:hidden property (#445)
  src/web/containers/Workspace/PrimaryWidgets.jsx
  src/web/containers/Workspace/SecondaryWidgets.jsx
  src/web/widgets/Axes/DisplayPanel.jsx
Labels: bug

#462 Fix for the lastQueryTime Marlin bug
  src/app/controllers/Marlin/MarlinController.js
Labels: Marlin, bug

#468 [Smoothie] Support new status format (#463)
  src/server/controllers/Smoothie/SmoothieLineParserResultStatus.js
  src/server/controllers/Smoothie/SmoothieRunner.js
  test/smoothie.js
Labels: Smoothieware, feature
