Repository cncjs/cncjs, pull requests merged in 2024-10, with the labels that each got.

#869 Update to node 18, webpack 5
  .github/workflows/ci-docker-hub.yml
  .github/workflows/ci.yml
  .gitignore
  Dockerfile
  package.json
  scripts/ci-docker-build.sh
  src/app/components/DatePicker/index.js
  src/app/components/Image/index.js
  src/app/components/Portal/index.js
  src/app/lib/chalk.js
  src/app/polyfill/console.js
  src/app/polyfill/index.js
  src/app/widgets/Axes/Settings/MDI/index.js
  src/app/widgets/Console/Terminal.jsx
  src/app/widgets/Console/index.jsx
  src/package.json
  src/server/config/settings.production.js
  test/evaluate-expression.js
  test/tinyg.js
  webpack.config.development.js
  webpack.config.production.js
  yarn.lock
Labels: dependencies, Bug fix, Enhancement, Review effort [1-5]: 3

#875 fix: resolve conflicting shortcut key assignments in `Combokeys`
  src/app/lib/combokeys.js
Labels: bug_fix, Review effort [1-5]: 1

#876 feat(`g2`, `tinyg`): add `jogCancel` command to cancel jogging using feedhold and queue flush
  src/server/controllers/TinyG/TinyGController.js
Labels: Enhancement, Review effort [1-5]: 2

#877 feat: allow anonymous usage data collection
  build.config.js
  examples/.cncrc
  package.json
  src/app/config/settings.js
  src/app/containers/Settings/About/About.jsx
  src/app/containers/Settings/About/CheckForUpdatesContainer.jsx
  src/app/containers/Settings/About/index.styl
  src/app/containers/Settings/General/General.jsx
  src/app/containers/Settings/Settings.jsx
  src/app/index.jsx
  src/app/lib/analytics.js
  yarn.lock
Labels: Enhancement, configuration changes, Review effort [1-5]: 4

#883 feat(Grbl): enhance Grbl parser to resolve issues with specific Grbl forks that generate incorrect parser state output ($G)
  src/server/controllers/Grbl/GrblLineParserResultParserState.js
  test/grbl.js
Labels: Enhancement, Review effort [1-5]: 3, Tests

#880 feat(Grbl): support UART communication without resetting the connection upon opening
  src/server/controllers/Grbl/GrblController.js
Labels: Enhancement, Review effort [1-5]: 3

#884 feat(l10n): upgrade `i18next-scanner` and refresh translations
  README.md
  build.config.js
  i18next-scanner.app.config.js
  i18next-scanner.server.config.js
  package.json
  src/app/constants/i18n.js
  src/app/containers/Settings/General/General.jsx
  src/app/i18n/cs/resource.json
  src/app/i18n/de/resource.json
  src/app/i18n/en/resource.json
  src/app/i18n/es/resource.json
  src/app/i18n/fr/resource.json
  src/app/i18n/hu/resource.json
  src/app/i18n/it/resource.json
  src/app/i18n/ja/resource.json
  src/app/i18n/nb/resource.json
  src/app/i18n/nl/resource.json
  src/app/i18n/pt-br/resource.json
  src/app/i18n/pt-pt/resource.json
  src/app/i18n/ru/resource.json
  src/app/i18n/tr/resource.json
  src/app/i18n/uk/resource.json
  src/app/i18n/zh-cn/resource.json
  src/app/i18n/zh-tw/resource.json
  yarn.lock
Labels: Enhancement, Review effort [1-5]: 2, other

#885 fix: resolve a regression where `api.getState` is only accessible only with an authenticated session
  src/app/containers/Login/Login.jsx
  src/app/index.jsx
Labels: Enhancement, Review effort [1-5]: 3, bug_fix

#887 docs: update outdated contribution guidelines
  CONTRIBUTING.md
  package.json
  webpack.config.development.js
Labels: Review effort [1-5]: 2

#888 build: utilize `react-fresh` for Fast Fresh integration
  .bowerrc
  .eslintrc.js
  babel.config.js
  package.json
  src/app/components/Image/index.js
  src/app/components/Portal/index.js
  src/app/containers/Settings/Commands/UpdateRecord.jsx
  src/app/polyfill/index.js
  src/app/widgets/Axes/Settings/MDI/index.js
  src/app/widgets/Custom/Settings.jsx
  src/server/config/settings.base.js
  webpack.config.development.js
  webpack.config.production.env
  webpack.config.production.js
  yarn.lock
Labels: Enhancement, Review effort [1-5]: 3, configuration changes
